### ISSUE TITLE
After stripping static archives, run ranlib

### ISSUE THREAD

**Issue by InBetweenNames** [mgorny/portage-mgorny#21]
Hi @mgorny,

Over at lto-overlay, we have been dealing with an issue involving `strip` being invoked on static archives that have LTO symbols.  In a nutshell, `strip` doesn't understand these symbols and mangles the index in these archives as a result.  The recommended way to fix them, according to upstream discussions from the binutils devs, is to run `ranlib` on them to fix the index afterwards.

Previously, we sidestepped the problem by setting `STRIP_MASK` to avoid stripping static archives.  However, that functionality is deprecated in EAPI 7, so I had to resort to patching Portage.  Fortunately, the workaround in portage is easy, with a three line fix to `estrip`:

https://github.com/InBetweenNames/gentooLTO/blob/master/sys-config/ltoize/files/patches/sys-apps/portage/lto.patch

I know there's no chance that the upstream Gentoo developers would accept such a fix, because it of course doesn't address the root problem: `strip` not using linker plugins like `AR`, `NM`, and `RANLIB` do.  The proper fix would be to fix `strip` to use the GCC linker plugin and not clobber the index when it sees an LTO symbol.  However, the upstream binutils developers have expressed no interest in doing that, and it's not hard to see why.

I was wondering, would you be willing to accept that patch into `sys-apps/portage-mgorny` as a workaround until a proper solution comes along?

**Comment by mgorny** [comment]
I don't see how much problem with that. However, shouldn't ranlib be run only for static archives? You don't need to update the patch, just want to confirm.

**Comment by InBetweenNames** [comment]
Yup -- it should.  That context is missing from the diff, but it's there.

**Comment by mgorny** [comment]
Ah, indeed. I'm going to implement this in slightly different way, and then see if we can integrate it into upstream Portage as well.

**Comment by InBetweenNames** [comment]
Excellent!  I like the way you implemented it more and I'll switch to your patch in lto-overlay instead of mine.  Thanks!
